#!/bin/bash
PARSED_MISSING=$1
[ -n "$PARSED_MISSING" ] || PARSED_MISSING=/srv/work/build/nomad-lab-base/parsers/quantum-espresso/parser/parser-quantum-espresso/testsuite.parsed_missing
perl -ne '@l=split; if ($l[0]==0) { $a=$l[1]; if ($a=~s/\.annotate//) { @g=glob "$a*"; print join("\n", @g) . "\n"; }}' $PARSED_MISSING | \
     xargs mv --target-directory=/srv/work/tmp/espresso/test-link-done/
